"""API-Key verifier — Stream C.3.

The bearer format is::

    aforge_pat_<5hex>_<32 url-safe random>

where ``<5hex>`` is a 5-character lowercase tenant-id prefix (visible in
logs / audit dashboards for quick identification — does not leak the
full tenant) and ``<32 random>`` is generated by :func:`secrets.token_urlsafe`.

The database stores **only** ``prefix = aforge_pat_<5hex>_`` (17 chars,
``UNIQUE``) plus the argon2id hash of the entire bearer. Verification:

1. Recognise the leading sentinel ``aforge_pat_`` — otherwise return
   ``None`` so :class:`AuthMiddleware` can try the next branch.
2. Split off the prefix and look it up; missing prefix → invalid.
3. Argon2id-verify the full bearer against ``secret_hash``; mismatch →
   invalid.
4. Reject revoked / expired keys.
5. Mint a service-account :class:`Principal` with the key's scopes.
"""

from __future__ import annotations

import logging
import secrets
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from uuid import UUID

from argon2 import PasswordHasher
from argon2.exceptions import VerificationError, VerifyMismatchError

from control_plane.auth.errors import InvalidTokenError, TokenExpiredError
from helix_agent.persistence.auth import ApiKeyStore
from helix_agent.protocol import (
    API_KEY_STORED_PREFIX_LEN,
    ApiKey,
    ApiKeyScope,
    Principal,
)

logger = logging.getLogger("helix.control_plane.auth.api_key")

#: Bearer sentinel — also a feature-flag of sorts: anything that does
#: not start with this is **not** an API key and the verifier returns
#: ``None`` so the JWT branch (or mTLS) can take over.
API_KEY_SENTINEL: str = "aforge_pat_"

#: Length of the stored ``prefix`` column. Keep in sync with
#: :data:`helix_agent.protocol.API_KEY_STORED_PREFIX_LEN`.
#: ``aforge_pat_<5hex>_<8 random hex>`` = 25 chars (Stream K.K1 widened the
#: prefix to fold 8 random hex into it, so two keys in the same tenant no
#: longer collide on the ``UNIQUE`` constraint).
API_KEY_PREFIX_LEN: int = API_KEY_STORED_PREFIX_LEN

#: Random tail length. 32 url-safe chars ≈ 192 bits — well above the
#: OWASP minimum for bearer tokens.
_RANDOM_TAIL_NCHARS: int = 32


@dataclass(frozen=True)
class GeneratedApiKey:
    """Returned by :func:`mint_api_key` — never persisted as-is."""

    plaintext: str
    prefix: str
    secret_hash: str


def is_api_key_bearer(token: str) -> bool:
    """Cheap pre-check used by :class:`AuthMiddleware`."""
    return token.startswith(API_KEY_SENTINEL)


def mint_api_key(*, tenant_id: UUID, hasher: PasswordHasher | None = None) -> GeneratedApiKey:
    """Generate a fresh API key + argon2id digest.

    The 5-hex prefix is derived from the first hex chars of ``tenant_id``
    so audit dashboards can group keys per-tenant at a glance.
    """
    tenant_short = tenant_id.hex[:5]
    random_tail = secrets.token_urlsafe(_RANDOM_TAIL_NCHARS)[:_RANDOM_TAIL_NCHARS]
    plaintext = f"{API_KEY_SENTINEL}{tenant_short}_{random_tail}"
    prefix = plaintext[:API_KEY_PREFIX_LEN]
    hasher = hasher or PasswordHasher()
    secret_hash = hasher.hash(plaintext)
    return GeneratedApiKey(plaintext=plaintext, prefix=prefix, secret_hash=secret_hash)


@dataclass
class ApiKeyVerifier:
    """Resolve a ``aforge_pat_*`` bearer → :class:`Principal`.

    A single instance is wired into :class:`AuthMiddleware` via the app
    factory; ``hasher`` is shared (Argon2 is stateless beyond the
    configured params).
    """

    store: ApiKeyStore
    hasher: PasswordHasher

    @classmethod
    def from_store(cls, store: ApiKeyStore) -> ApiKeyVerifier:
        return cls(store=store, hasher=PasswordHasher())

    async def verify(self, bearer: str) -> Principal:
        if not is_api_key_bearer(bearer):
            # Caller should have checked first; raising matches the JWT
            # path which also raises on unrecognised tokens.
            raise InvalidTokenError()
        if len(bearer) < API_KEY_PREFIX_LEN:
            raise InvalidTokenError()
        prefix = bearer[:API_KEY_PREFIX_LEN]

        record: ApiKey | None = await self.store.get_by_prefix(prefix=prefix)
        if record is None:
            # Constant-time-ish: spend one argon2id verify against a
            # dummy hash to avoid leaking "prefix exists" via timing.
            self._dummy_verify(bearer)
            raise InvalidTokenError()
        if record.revoked_at is not None:
            raise InvalidTokenError()
        # Stream K.K1 (Mini-ADR K-1) — a rotated key keeps verifying
        # until ``rotated_at + grace_period_s`` elapses; after that the
        # old bearer is dead and clients must use the replacement.
        if record.rotated_at is not None and record.grace_period_s is not None:
            grace_expires = record.rotated_at + timedelta(seconds=record.grace_period_s)
            if datetime.now(UTC) >= grace_expires:
                raise InvalidTokenError()
        if record.expires_at is not None and record.expires_at < datetime.now(UTC):
            raise TokenExpiredError()
        try:
            self.hasher.verify(record.secret_hash, bearer)
        except (VerifyMismatchError, VerificationError):
            raise InvalidTokenError() from None

        # Best-effort last-used update — never blocks the request.
        try:
            await self.store.touch_last_used(api_key_id=record.id, when=datetime.now(UTC))
        except Exception:
            logger.exception("api_key.touch_last_used_failed", extra={"key_id": str(record.id)})

        return Principal(
            subject_id=str(record.service_account_id),
            subject_type="service_account",
            tenant_id=record.tenant_id,
            roles=("service_account",),
            scopes=tuple(s.value for s in record.scopes),
            auth_method="api_key",
            allowed_tenants=(record.tenant_id,),
        )

    def _dummy_verify(self, bearer: str) -> None:
        """Burn ~argon2id cost so prefix-miss timing matches prefix-hit.

        Argon2id always raises on mismatch — we deliberately discard the
        exception (anti-timing pad) and never log it (logging the dummy
        miss every request would flood the structured-log stream).
        """
        try:
            self.hasher.verify(_DUMMY_HASH, bearer)
        except Exception:
            return


#: A pre-computed argon2id hash of an opaque value, used to keep the
#: prefix-miss branch as costly as the prefix-hit branch (anti-timing).
_DUMMY_HASH: str = PasswordHasher().hash("not-a-real-secret-do-not-use")


def supports_scope(principal_scopes: Sequence[str], required: ApiKeyScope) -> bool:
    """Tiny helper used by the RBAC layer (api_key path)."""
    if not principal_scopes:
        return False
    return required.value in principal_scopes or ApiKeyScope.ADMIN.value in principal_scopes
