"""``/v1/tenants`` tenant-provisioning endpoint — Stream P (Mini-ADR P-1/P-2/P-5).

``POST /v1/tenants`` is the explicit "create a tenant" action. It is a
**platform-level** operation — provisioning a brand-new RLS scope — so it is
gated on ``is_system_admin`` directly (Mini-ADR P-2: a tenant ADMIN must not
be able to mint other tenants, hence no ``tenant`` RBAC resource). The write
runs inside :func:`bypass_rls_session` because the new ``tenant_id`` differs
from the caller's request-scoped ``app.tenant_id`` and the FORCE-RLS
``tenant_config`` policy would otherwise reject the insert.

Listing/reading/configuring an existing tenant lives in ``tenant_config`` /
``tenant_quotas`` (which share this ``/v1/tenants`` prefix); the bare
``POST ""`` here does not collide with their ``{tenant_id}/...`` paths.
"""

from __future__ import annotations

import logging
from typing import Annotated
from uuid import UUID, uuid4

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, ConfigDict, Field

from control_plane.api._authz import _principal
from control_plane.audit import emit
from control_plane.tenant_scope import bypass_rls_session
from helix_agent.common.observability import current_trace_id_hex
from helix_agent.persistence.tenant_config.base import (
    TenantConfigAlreadyExistsError,
    TenantConfigStore,
)
from helix_agent.protocol import AuditAction, Principal, TenantPlan
from helix_agent.runtime.audit.logger import AuditLogger

logger = logging.getLogger("helix.control_plane.api.tenants")


class CreateTenantRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")
    # Server-generated by default; a client-supplied UUID supports idempotent
    # provisioning from an upstream system (Mini-ADR P-5).
    tenant_id: UUID | None = None
    display_name: str = Field(min_length=1, max_length=128)
    plan: TenantPlan | None = None


def _get_repo(request: Request) -> TenantConfigStore:
    return request.app.state.tenant_config_repo  # type: ignore[no-any-return]


def _get_audit(request: Request) -> AuditLogger:
    return request.app.state.audit_logger  # type: ignore[no-any-return]


def build_tenants_router() -> APIRouter:
    router = APIRouter(prefix="/v1/tenants", tags=["tenants"])

    @router.post("", status_code=201)
    async def create_tenant(
        payload: CreateTenantRequest,
        principal: Annotated[Principal, Depends(_principal)],
        repo: Annotated[TenantConfigStore, Depends(_get_repo)],
        audit: Annotated[AuditLogger, Depends(_get_audit)],
    ) -> dict[str, object]:
        # Mini-ADR P-2 — tenant creation is platform-level; only system admins.
        if not principal.is_system_admin:
            raise HTTPException(
                status_code=403,
                detail={
                    "code": "PLATFORM_SCOPE_FORBIDDEN",
                    "message": "only a system admin may create tenants",
                },
            )
        tenant_id = payload.tenant_id or uuid4()
        # The new tenant_id is not the caller's home tenant, so the write +
        # its audit row must bypass RLS (Mini-ADR P-1, risk: audit-in-bypass).
        async with bypass_rls_session():
            try:
                record = await repo.create(
                    tenant_id=tenant_id,
                    display_name=payload.display_name,
                    plan=payload.plan,
                    actor_id=principal.subject_id,
                )
            except TenantConfigAlreadyExistsError as exc:
                raise HTTPException(
                    status_code=409,
                    detail={
                        "code": "TENANT_ALREADY_EXISTS",
                        "message": "a tenant with this id already exists",
                    },
                ) from exc
            await emit(
                audit,
                tenant_id=tenant_id,
                actor_id=principal.subject_id,
                action=AuditAction.TENANT_CREATE,
                resource_type="tenant",
                resource_id=str(tenant_id),
                trace_id=current_trace_id_hex(),
                details={"display_name": record.display_name, "plan": record.plan.value},
            )
        return {"success": True, "data": record.model_dump(mode="json"), "error": None}

    return router
